Add missing #include <algorithm> required for std::clamp
Fixes:
2026-01-20T14:13:33.5700853Z  │ │ $SRC_DIR/ros-kilted-autoware-trajectory/src/work/include/autoware/trajectory/interpolator/detail/interpolator_common_interface.hpp:99:17: error: 'clamp' is not a member of 'std'
2026-01-20T14:13:33.5720998Z  │ │    99 |     return std::clamp(s, start(), end());
2026-01-20T14:13:33.5737233Z  │ │       |                 ^~~~~